name: Build & Publish Multi-Arch Hugo Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Get source
      - name: Checkout source
        uses: actions/checkout@v3

      # 2. Install Hugo
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.128'

      # 3. Build site
      - name: Build site
        run: hugo --minify

      # 4. Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Build & push multi-arch image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/hugo-nginx:latest
            ghcr.io/${{ github.repository_owner }}/hugo-nginx:${{ github.sha }}
